# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Mauritania' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'DocumentReader'
	pod 'DocumentReaderFullRFID'
  pod 'Alamofire'
  pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress'
  pod 'ALProgressView'
  pod 'lottie-ios'
  pod 'MercariQRScanner'
  pod 'ActionSheetPicker-3.0'
  # Pods for Mauritania

end
